name: iotemplateapp
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pyyaml
  - tomli
  - tomli-w
  - virtualenv
  - pip
  - pip:
    - git+https://IoAeroMachineUser:${PYPI_PAT}@github.com/io-aero/io-common.git
    - git+https://@github.com/io-aero/io-template-lib.git
