name: iotemplateapp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pyyaml
  - pip:
      - git+https://IoAeroMachineUser:${PYPI_PAT}@github.com/io-aero/io-common.git
      - git+https://@github.com/io-aero/io-template-lib.git
      - tomli
      - tomli-w
      - virtualenv
      # Development dependencies
      - bandit
      - black
      - coverage
      - coveralls
      - docformatter
      - furo
      - ipython
      - mypy
      - myst-parser
      - nuitka
      - ordered-set
      - pylint
      - pytest
      - pytest-cov
      - pytest-deadfixtures
      - pytest-helpers-namespace
      - pytest-random-order
      - rinohtype
      - ruff
      - sphinx
      - sphinx-autodoc-typehints
      - types-pyyaml
      - types-toml
      - vulture

