# Copyright (c) 2022-2023 IO-Aero. All rights reserved. Use of this
# source code is governed by the IO-Aero License, that can
# be found in the LICENSE.md file.

"""Module stub file."""
import argparse

ARG_TASK: str

def check_arg_task(args: argparse.Namespace) -> None: ...
def cleansing_postgres_data() -> None: ...
def create_db_schema() -> None: ...
def get_args() -> None: ...
def initialise_logger() -> None: ...
def load_aircraft_data() -> None: ...
def load_airport_data() -> None: ...
def load_runway_data() -> None: ...
def progress_msg(msg: str) -> None: ...
def progress_msg_time_elapsed(duration: int, event: str) -> None: ...
def refresh_db_schema() -> None: ...
def terminate_fatal(error_msg: str) -> None: ...
def update_db_schema() -> None: ...
def verify_ntsb_data() -> None: ...
def version() -> str: ...
