name: Standard

on:
  pull_request:
    branches: ['main']

env:
  IO_COVERALLS: 'false'
  IO_DOCKER: 'false'
  IO_ODBC: 'false'
  PYPI_PAT: ${{ secrets.PYPI_PAT }}

jobs:
  standard:
    name: OS ${{ matrix.os }} - Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, ubuntu-latest]
#       os: [ubuntu-latest]
        python-version: ["3.12"]

    steps:
      - name: Show the environment variables
        run: |
          echo "IO_COVERALLS= ${{ env.IO_COVERALLS }}"
          echo "IO_DOCKER   = ${{ env.IO_DOCKER }}"
          echo "IO_LOCAL    = ${{ vars.IO_LOCAL }}"
          echo "IO_ODBC     = ${{ env.IO_ODBC }}"

      - name: Set Timezone
        run: echo "TZ=UTC" >> $GITHUB_ENV

      - name: Checking out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # no history, just HEAD

      - name: Set Locale - macOS
        if: runner.os == 'macOS'
        run: |
          echo "LANG=en_US.UTF-8" >> $GITHUB_ENV
          echo "LC_ALL=en_US.UTF-8" >> $GITHUB_ENV

      - name: Set Locale - Ubuntu
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y locales
          sudo locale-gen en_US.UTF-8
          sudo update-locale LANG=en_US.UTF-8

      - name: Preparing scripts - macOS
        if: runner.os == 'macOS'
        run: |
          brew install dos2unix
          chmod +x scripts/run_prep_*.zsh
          ./scripts/run_prep_zsh_scripts.zsh

      - name: Preparing scripts - Ubuntu
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update && sudo apt-get install -y dos2unix
          chmod +x scripts/run_prep_*.sh
          ./scripts/run_prep_bash_scripts.sh

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          miniconda-version: "latest"
          python-version: ${{ matrix.python-version }}

      - name: Install Docker - macOS
        if: ${{ env.IO_DOCKER == 'true' && runner.os == 'macOS' }}
        run: |
          brew install --cask docker
          open /Applications/Docker.app   

      - name: Set up Docker - Ubuntu
        if: ${{ env.IO_DOCKER == 'true' && runner.os == 'Linux' }}
        uses: docker/setup-buildx-action@v3

      - name: Install ODBC - macOS
        if: ${{ env.IO_ODBC == 'true' && runner.os == 'macOS' }}
        run: |
          brew update
          brew upgrade unixodbc

      - name: Install ODBC - Ubuntu
        if: ${{ env.IO_ODBC == 'true' && runner.os == 'Linux' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y unixodbc-dev

      - name: Install dependencies - Conda - prod
        run: make conda-prod

      - name: Compile the Python code - prod
        run: |
          conda init --all
          source ~/.bashrc
          conda activate iotemplateapp
          make compileall

      - name: Run pytest - prod
        run: |
          make pytest-ci

      - name: Install dependencies - Conda - dev
        run: make conda-dev

      - name: Run pytest - dev
        run: |
          conda init --all
          source ~/.bashrc
          conda activate iotemplateapp
          make black lint docs tests

      - name: Coveralls
        if: ${{ env.IO_COVERALLS == 'true' && runner.os == 'Linux' }}
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage.lcov
          flag-name: run-${{ matrix.os }}-py${{ matrix.python-version }}
          parallel: false
          parallel-finished: true
